# -*- coding: utf-8 -*-
"""task 3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oyjByMU8IDos7ngjYN1wSRpOsdpjA0q6
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df=pd.read_csv('/content/menu (1).csv')
df

df.head()

df.tail()

df.info()

df.shape

df.isnull().sum()

df.columns

#finding outliers
numeric_columns = df.select_dtypes(include=['number']).columns

for column in numeric_columns:
    plt.figure(figsize=(8, 4))
    plt.boxplot(df[column], vert=False)
    plt.title(f"Box Plot for {column}")
    plt.xlabel(column)
    plt.show()

# Removing outliers using IQR method
for column in numeric_columns:
    Q1 = np.percentile(df[column], 25)
    Q3 = np.percentile(df[column], 75)
    IQR = Q3 - Q1
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    df = df[(df[column] >= lower_bound) & (df[column] <= upper_bound)]

#Checking again for outliers using box plots after removal
for column in numeric_columns:
    plt.figure(figsize=(8, 4))
    plt.boxplot(df[column], vert=False)
    plt.title(f"Box Plot After Outlier Removal for {column}")
    plt.xlabel(column)
    plt.show()

df

df.shape

df.isnull().sum()

df.to_csv('menu.csv')

cf=pd.read_csv('/content/menu.csv')

cf.shape

cf

cf.isnull().sum()